jobs:
  contract_verify_job:
    runs-on: ubuntu-latest
    name: Verify smart contract files
    steps:
      # Checkout repo to use files of the repo as input for container action
      - name: Checkout
        uses: actions/checkout@v4
      - name: Contract verify action step
        uses: Franziska-Mueller/qubic-contract-verify@v0.3.3-beta
        with:
          filepaths: 'src/contracts/RandomLottery.h'
